### ISSUE TITLE
v1.9.0: Planned features

### ISSUE THREAD

**Issue by rangav** [rangav/thunder-client-support#282]
Hi All, Here is the list of planned features for v1.9.0

### New Features
- [x] **Collection level** auth, headers & Tests #33
- [x] Ability to **attach ENV** to a specific collection #173
- [x] Set Env Variable with scope option https://github.com/rangav/thunder-client-support/issues/33#issuecomment-890531732
- [x] Support for **Path Variables** #23
- [x] **Binary file** upload #273
- [x] Tests **regex match** option for tests like email, url #57
- [x] Button to clear cookies #271
- [x] Live Syntax Checking for JSON body #263 
- [x] Add Convert Javascript Object to JSON #285 
- [x] System variable randomNumber with custom range   #270
- [x] System variable date with **custom format** #256 
- [x] Codegen C# does not include 'File' form body fields #288
- [x] Show selected "Environment" on Request Page #159
- [x] Code Snippet support for **PowerShell** 

any questions or feedback comment below

**Comment by gimzani** [comment]
Can you please have a better way to save requests without relying on "Activity" and "Send".  I keep overwriting my saved requests and when I go back, they're a mess.

Thanks!

**Comment by rangav** [comment]
Hi @gimzani can you provide more details of the issue you are facing with examples/ screenshots 

and the solution you are expecting or how you want it to work?

**Comment by glaucoleme** [comment]
> Can you please have a better way to save requests without relying on "Activity" and "Send". I keep overwriting my saved requests and when I go back, they're a mess.
> 
> Thanks!

You can actually save it by pressing `cmd/ctrl + s`, since version 1.8.0

**Comment by gimzani** [comment]
I know now that "ctrl + s" will save - but it would be great to have a Save Button.  :)

**Comment by rangav** [comment]
Hi @gimzani please see this comment https://github.com/rangav/thunder-client-support/issues/238#issuecomment-887655060

**Comment by hadnet** [comment]
@rangav can you make the Enter Url input to has a dropdown showing the history of Url recently used?

**Comment by hadnet** [comment]
@rangav it would be great if you can (1) add a dropdown showing the history of url used in Enter Url input and (2) a function in order to convert JS objects into JSON object in the body JSON Content (like the Format you add it in order to format the JSON). Thanks for your work, man.

**Comment by rangav** [comment]
Hi @hadnet for no 2. Where you want the function, can you provide your use-case with example?

**Comment by hadnet** [comment]
> Hi @hadnet for no 2. Where you want the function, can you provide your use-case with example?

For example, at coding I model a JS object with many props and then I need to test it with an POST endpoint that request that object model. So it would be great just to copy that object and paste it in the request json content and with a button transform that JS object to a JSON object. It would the same as the function Format you added it. Currently in or
der to avoid doing all that transformation manually I use https://www.convertsimple.com/convert-javascript-to-json/. It would bet great if Thunder could have that Js to JSON function button: 
<img width="511" alt="Screen Shot 2021-07-31 at 3 28 31 PM" src="https://user-images.githubusercontent.com/13828833/127749358-160a4516-c07d-41cd-b472-7b3b29c4fdc6.png">

**Comment by rangav** [comment]
@hadnet got it, can you please create a new feature request for this, so we can track it there

**Comment by hadnet** [comment]
@rangav done. Thanks, man.

**Comment by nghtstr** [comment]
This will be a major update to this already awesome utility! One question that I have (and one probably all of us have), is when do you think you might be rolling it out? No pressure here, just wanting to know if it is going to be available for my cake day. 😜

**Comment by rangav** [comment]
Hi @nghtstr planning to release next week
when is your cake day?

**Comment by nghtstr** [comment]
My cake day was yesterday. Moved up to Level 44!

**Comment by rangav** [comment]
Oops we missed it :), next time we can plan early, anyway belated wishes to you 🎂

**Comment by rangav** [comment]
Hi all, Published this release v1.9.0
https://github.com/rangav/thunder-client-support/releases/tag/v1.9.0

This is major release will lot of features, please notify us if you notice any bugs.

**Comment by AWDDude** [comment]
Any way to save a collection to a file in a git repo? It would be really useful to be able to have requests versioned along side the server code its querying. This would also make it easy to share amoung a team.

**Comment by rangav** [comment]
Hi @AWDDude 
Please see details here
https://github.com/rangav/thunder-client-support#team

**Comment by CyberCitizen01** [comment]
Hi @rangav, First of all, I want to appreciate all of you for this amazing extension 🎉 , It really helps a lot!!
I was thinking that it would be so nice to have support for `WebSocket`s, because why not... I mean, atleast I would write dummy html files to test my socket server...which sometimes can be very cumbersome. It would just be so nice to test these within VS code, combined with the awesome simple UI of Thunder Client. I really hope we get this for the next release 🤞🏻

**Comment by rangav** [comment]
Thanks @CyberCitizen01 for the awesome feedback.

We have websockets in the roadmap, currently working for Team features once I finish, then I can look into websocket. 

#3 have a dedicated issue for this

**Comment by rangav** [comment]
Hi @leandro-toledo-uux, thanks for the feedback.

can you please create a separate request for the unsaved Indicator, so we can track it there

I will add this to roadmap.
